services:

    app-auth:
        container_name: "app-auth"
        build:
            context: .
            dockerfile: backend/auth/Dockerfile
        env_file:
            - backend/auth/env/app.env
        ports:
            - "8000:8000"
        restart: unless-stopped

    app-dashboard:
        container_name: "app-dashboard"
        build:
            context: .
            dockerfile: backend/dashboard/Dockerfile
        env_file:
            - backend/dashboard/env/app.env
        ports:
            - "8001:8001"
        restart: unless-stopped

    nginx:
        container_name: "nginx"
        image: nginx:alpine
        volumes:
            - ./nginx/dev.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        depends_on:
            - app-auth
            - app-dashboard
