services:

    app-frontend:
        container_name: "app-frontend"
        build:
            context: .
            dockerfile: ./docker/Dockerfile.frontend
        env_file:
            - ./frontend/env/app.env
        ports:
            - "8000:8000"
        restart: unless-stopped

    app-auth:
        container_name: "app-auth"
        build:
            context: .
            dockerfile: ./docker/Dockerfile.auth
        env_file:
            - ./backend/auth/env/app.env
        ports:
            - "8001:8001"
        restart: unless-stopped

    app-dashboard:
        container_name: "app-dashboard"
        build:
            context: .
            dockerfile: ./docker/Dockerfile.dashboard
        env_file:
            - ./backend/dashboard/env/app.env
        ports:
            - "8002:8002"
        restart: unless-stopped

    nginx:
        container_name: "nginx"
        image: nginx:alpine
        volumes:
            - ./nginx/config/dev.conf:/etc/nginx/nginx.conf:ro
        ports:
            - "80:80"
        depends_on:
            - app-frontend
            - app-auth
            - app-dashboard
