FROM python:3.9-slim

WORKDIR /app

COPY ./backend/auth /app
COPY ./backend/packages/shared/auth /app/packages/shared/auth

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
