FROM python:3.9-slim

WORKDIR /app

# Backend
COPY ./backend/dashboard /app
COPY ./backend/packages/shared/auth /app/packages/shared/auth

# Frontend
COPY ./frontend/ /app/frontend/

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8002

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
