events {}
http {

    # Server Name Indication (SNI) support for SSL/TLS proxying
    proxy_ssl_server_name on;

    # Server Configurations
    server {

        # Port
        listen 80;

        # =========================
        # Main
        # =========================

        location = / {
            return 303 /login;
        }

        location /static/ {
            proxy_pass http://app-auth:8000/static/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # =========================
        # API
        # =========================

        location /login {
            proxy_pass http://app-auth:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /auth/api/ {
            proxy_pass http://app-auth:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # =========================
        # Dashboard
        # =========================

        location /dashboard {
            proxy_pass http://app-dashboard:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
