events {}
http {

    # Server Name Indication (SNI) support for SSL/TLS proxying
    proxy_ssl_server_name on;

    # Server Configurations
    server {

        # Port
        listen 80;

        # =========================
        # Entry Point
        # =========================

        location = / {
            return 302 /login;
        }

        # =========================
        # Authentication
        # =========================

        location /login {
            proxy_pass https://uninsubria-rvicario-ws-auth.onrender.com;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /auth/api {
            proxy_pass https://uninsubria-rvicario-ws-auth.onrender.com;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # =========================
        # Dashboard
        # =========================

        location /dashboard {
            proxy_pass https://uninsubria-rvicario-ws-dashboard.onrender.com;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
